version: "3.0"
services:
  dockerapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks: 
      - my_net
  redis:
    image: redis:3.2.4
    networks: 
      - my_net

networks: 
  my_net:
    driver: bridge